
training:
  epochs: 90
  batch_size: 128
  input_size: (227,227,3)
    patience: 3

model:
  dir: models
  name: imagenet_a

data:
  crop_amount: 1048
  dataset: imagenet_a

checkpoint:
  name: "alexnet"
  dir: "./checkpoints"
  max_to_keep: 3

optimizer:
  learning_rate: 0.0005
  momentum: 0.9

tensorboard:
  dir: logs
  debug: False
