
training:
  epochs: 3
  batch_size: 128
  input_size: (227,227,3)
  patience: 3
  
data:
  dataset: imagenette/full-size-v2
  split: train
  crop_amount: 2
  augment: False

checkpoint:
  name: "alexnet"
  dir: "./checkpoints"
  max_to_keep: 3

optimizer:
  learning_rate: 0.01
  momentum: 0.9

tensorboard:
  dir: logs
  debug: True
