
training:
  epochs: 3
  batch_size: 128
  input_size: (227,227,3)

model:
  dir: models
  name: imagenet_a
  
data:
  crop_amount: 2
  dataset: imagenet_a

checkpoint:
  name: "alexnet"
  dir: "./checkpoints"
  max_to_keep: 3

optimizer:
  learning_rate: 0.1
  momentum: 0.9

tensorboard:
  dir: logs
